// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrdersData;

#nullable disable

namespace OrdersData.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20220620171502_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OrdersData.Entities.Customer", b =>
                {
                    b.Property<string>("CustomerEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerFName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerLName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerPhone")
                        .HasColumnType("int");

                    b.HasKey("CustomerEmail");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("OrdersData.Entities.Item", b =>
                {
                    b.Property<string>("ItemName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ItemQty")
                        .HasColumnType("int");

                    b.Property<int?>("ItemsRate")
                        .HasColumnType("int");

                    b.HasKey("ItemName");

                    b.ToTable("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
